set_property SRC_FILE_INFO {cfile:/home/skravitz/RFSOC/project_1/project_1.srcs/constrs_1/new/base.xdc rfile:../../../project_1.srcs/constrs_1/new/base.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN13 [ get_ports "sw[0]" ]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU12 [ get_ports "sw[1]" ]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW11 [ get_ports "sw[2]" ]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV11 [ get_ports "sw[3]" ]
